### ISSUE TITLE
[contracts] Interface changes

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1080]
Need to finalize interface changes that we have gotten suggestions on from users.

Things that could be important:
- [x] adding in a `receivingAsset` that can be the local or adopted asset for that chain
- [ ] adding in a way to specify slippage boundaries
- [x] ~~adding in `xcallExactOut` path~~ -> can do this in an upgrade since only additive if needed
- [x] specifying if you want to use slow or fast liquidity
- [x] add `getExecutor()` to `IConnextHandler.sol` to expose the executor via interface. similar to how we have `getConnext()` in `IExecutor.sol`

cc @just-a-node -- if there's any other feedback you've been getting now is the time to surface it!

**Comment by LayneHaber** [comment]
another could be:

- adding a `user` or `submitter` -- basically someone who isn't explicitly listed as a relayer who can relay that specific transaction (handle the case where relayers are unavailable and user self-submits)

**Comment by just-a-node** [comment]
> specifying if you want to use slow or fast liquidity

Now do we need sanity checks for XCallArgs given slow/fast liquidity can be specified?

e.g. user wants fast liquidity but includes calldata that can't go through fast path. or user wants slow liquidity but the transaction can actually go through fast path (why would they prefer slow?)

**Comment by LayneHaber** [comment]
> e.g. user wants fast liquidity but includes calldata that can't go through fast path. or user wants slow liquidity but the transaction can actually go through fast path (why would they prefer slow?)

him this is a good point -- here it should still fail and force users into the slow liquidity path even if fast liquidity was specified. there's no realistic way for us to check the permissions for the calldata on `xcall` unfortunately.

users could prefer the slow path if they dont want to take the 0.05% fee on a transfer

if this isn't needed, can totally remove this requirement! i just believe it came up before so included it

**Comment by just-a-node** [comment]
> hm this is a good point -- here it should still fail and force users into the slow liquidity path even if fast liquidity was specified. there's no realistic way for us to check the permissions for the calldata on `xcall` unfortunately.
> 
> users could prefer the slow path if they dont want to take the 0.05% fee on a transfer
> 
> if this isn't needed, can totally remove this requirement! i just believe it came up before so included it

I feel less inclined toward allowing users to specify fast liquidity if it ends up slow - this could feel like bad UX. However, actively choosing to go slow and save on the 0.05% fee is definitely a nice option that I think we should surface. 

Could we add a param like `force-slow` that explicitly only allows the slow option in these cases?

**Comment by just-a-node** [comment]
Another request:

- add `getExecutor()` to `IConnextHandler.sol` to expose the executor via interface. similar to how we have `getConnext()` in `IExecutor.sol`

**Comment by LayneHaber** [comment]
Some interesting edge cases come up around the slippage boundaries, specifically for the `execute` function.

### Purpose

The purpose of defining slippage boundaries is to ensure users do not unwittingly lose funds when they are sent over the bridge and swapped using the AMM. Typically, these boundaries are defined as a percent or as a `minAmountReceived` and if the minimum is *not* met (or you get less than x% of your input), the transaction will revert.

### Considerations

**Accounting for Router Fees** (easy)
This mostly has to do with the best way to convey slippage through the API. If you define the slippage as a minimum received from the swap, then you can either:

1. Define a single `minimum` for both the destination and receiving chains. Because the router takes its liquidity fees *before* the swap occurs, the singular amount defined must account for this fee when swapping. This means the user will be forced into accepting higher than necessary slippage on the origin chain.
2. Define a single `percent` for both the destination and receiving chains. This would be assessed after router fees were taken, so could easily be consistent between chains. Would require the numerator and denominator to be specified separately.
3. Define `minimum`s for the destination and receiving chains separately. This works, but would require the user to calculate the fees up front to determine the appropriate `minimum` for the destination chain.

Of all of these options, I am in favor of (2).

**Accounting for Failures on the Destination Chain** (hard)
The more difficult edgecase handling comes into play when these slippage conditions are violated. On the origin chain, this simply looks like the `xcall` reverting, which is manageable by the users themselves. However on the destination chain the `execute` would revert, and would continue to reverting until the AMM falls into the specified boundary conditions again (which would take an indeterminate amount of time).

There are a few possible solutions to this:

1. *Allow the failure*. This means that slippage would only be enforced on the origin chain, and not the destination chain. This is problematic because the user is not at all insulated from slippage. The AMM itself is a stable swap and slippage would should only be problematic for large transfers or transfers occurring when the pools are heavily imbalanced
2. *Force users to wait*. This would not allow the users to `execute` a transfer while the boundary conditions are not met. With active arbitrageurs the pools should stay in balance, but there is no limit to how long it would take to ensure the pools are balanced. Further, in the case of large transfers you are not simply waiting for the pools to balance but for increased liquidity depth.
3. *Permissioned Slippage Adjustments*. This is the only realistic solution to this problem if we want to protect users from slippage, while not holding funds hostage. By using the `adjustSlippage(transferId)` function, users could specify any slippage on the destination chain at any time. However, this change in slippage must be authenticated, meaning the escape hatch must be called by the user themselves (or a user defined `initiator`) or contain a signature from the user permitting the change in slippage. The UX here is annoying, but some type of escape hatch is needed to release funds if pool conditions undergo a sustained change.

**Comment by jakekidd** [comment]
*Accounting for Failures . 3*:
> However, this change in slippage must be authenticated, meaning the escape hatch must be called by the user themselves (or a user defined initiator) or contain a signature from the user permitting the change in slippage.

I am in favor of the latter of the two options ( calling on chain vs just an update signature ). If we're going to create a liveness assumption to solve this problem, then we might as well lean into it appropriately. Implement an API endpoint on the sequencer agent to accept signed "slippage adjustments" from users. Would actually be fairly simple to do that for now.

It's definitely worth acknowledging here that the latter problem *does not exist* if destination is a canonical chain / asset, because there is no stableswap in execute for that. Therefore, it wouldn't be *entirely* exclusive to implement this liveness-assumption option for non-canonical-destination cases; developers trying to build xapp systems that use `minAmount` and have no liveness dependencies can be advised to swap to an asset that is canonical on their destination.

(For example, if you're going to Gnosis  from any chain, and want to use min amount, you should swap to using the wrapped xDai on your current chain and then bridge to Gnosis with min amount defined.)

Not ideal, but it means there's still an option for live-less development lol.

**Comment by LayneHaber** [comment]
> I am in favor of the latter of the two options ( calling on chain vs just an update signature ). If we're going to create a liveness assumption to solve this problem, then we might as well lean into it appropriately. Would actually be fairly simple to implement an API endpoint on the sequencer agent to accept signed "slippage adjustments" from users.

This won't work for daos caught in the slippage limbo -- you would need to offer both options.

> It's definitely worth acknowledging here that the latter problem does not exist if destination is a canonical chain / asset, because there is no stableswap in execute for that.

Correct, also does not exist when the mad asset is the adopted asset.

**Comment by jakekidd** [comment]
> This won't work for daos caught in the slippage limbo -- you would need to offer both options.

Sad, but you right

**Comment by jakekidd** [comment]
One thing we could tack on here - what happens if the user is *deeeply* dissatisfied with the slippage? Like, so dissatisfied, they'd rather just send their money back?

If the funds get stuck (as in 1.) and the user isn't willing to raise the slippage tolerance, then they should be able to `reject` the call and send it back, right?

**Comment by just-a-node** [comment]
> One thing we could tack on here - what happens if the user is _deeeply_ dissatisfied with the slippage? Like, so dissatisfied, they'd rather just send their money back?
> 
> If the funds get stuck (as in 1.) and the user isn't willing to raise the slippage tolerance, then they should be able to `reject` the call and send it back, right?

+1 to having a full abort mechanism. Instead of being forced to accept unreasonable slippage if there's time sensitivity, users should have the option to cut their losses (on transaction fees) and send it right back.

**Comment by rhlsthrm** [comment]
Instead of sending it back through the bridge, they should just be able to retrieve their funds in madAssets and they can send back manually later right? We can wrap this up in a UI but I don't think this needs to explicitly be part of the protocol.

**Comment by jakekidd** [comment]
> Instead of sending it back through the bridge, they should just be able to retrieve their funds in madAssets and they can send back manually later right? We can wrap this up in a UI but I don't think this needs to explicitly be part of the protocol.

This would still require interface changes, afaik.

ex:
Chain **A** => **B**
Asset **UA** => **MA** => **MB** => **UB**
- User sends 100 **UA**, wants to receive at least 98 **UB**.
- Ignore slippage **UA** => **MA**, as that can be handled atomically.
- By the time user's 100 **MA** gets delivered to receiving chain, slippage/ratio for **MB** => **UB** is now 100:97.
- No routers can execute fast-liq because 97 < 98; `execute` would revert.
- After 30 minutes, **MB** comes through, and the slippage stays the same.
- But `reconcile` slow-liq route will revert because the slippage is too high.

So either one of these things needs to happen:
- If, in `reconcile`, the slippage (or ratio) for swap is too high to get the desired asset (i.e. user's `minAmount` would not be met) we just **fallback** to sending user **MB** instead. They can choose to wait and swap it later or send it back, etc.
- If we don't like this **fallback** behavior happening without user's explicit consent, we can allow the user to specify a `minAmountExpiry`. After this period of time (15 minutes, 30 minutes, 1 hour, etc.), if the `minAmount` still can't be met, `execute` and/or `reconcile` can then be called, but it will **fallback** to sending **MB**.
- Create an `abort` path where a user can send funds back after they've been confirmed on the receiving chain.

**Comment by LayneHaber** [comment]
> Instead of sending it back through the bridge, they should just be able to retrieve their funds in madAssets and they can send back manually later right? We can wrap this up in a UI but I don't think this needs to explicitly be part of the protocol.

so you're saying just give users a way to manually pull out the unexecuted mad assets and allow them to unwrap by sending back to origin or canonical domain?

**Comment by rhlsthrm** [comment]
> > Instead of sending it back through the bridge, they should just be able to retrieve their funds in madAssets and they can send back manually later right? We can wrap this up in a UI but I don't think this needs to explicitly be part of the protocol.
> 
> so you're saying just give users a way to manually pull out the unexecuted mad assets and allow them to unwrap by sending back to origin or canonical domain?

Yes exactly. This seems easier and works with the current protocol.

**Comment by LayneHaber** [comment]
We could have an override for pulling out the local assets -- will create a separate issue for this. 

Sending back through natively has a few weird UX questions:
1. Would have costs associated with relayer fees in the destination chain asset
2. Requires user to have gas on the destination chain to withdraw/send back through nomad
3. It's not clear if you should route to the *canonical* domain (so user gets unwrapped asset without AMM), any domain with more favorable slippage rates, or the origin domain. The weird part about going to the canonical domain is the user may not have ever interacted with that domain. Going to any domain with more favorable slippage conditions has a couple of issues -- the user may not have ever interacted with the domain and the slippage conditions may not hold. Going back to the origin domain ensures the user interacted with that domain, but there is no guarantee the slippage holds.

That being said, the simplest solution is to deliver the wrapped asset as an emergency escape hatch, and allow the user to make the decision about what to do with their funds.

**Comment by LayneHaber** [comment]
Closing, continuing above discussion in #1227
