### ISSUE TITLE
User can see Pool liquidity metrics

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#1535]
# Problem
Users want to view 
- How much net liquidity (TVL) is in a Pool
- How much liquidity they have provided 

# Definition of Done
- [ ] Pool metrics are queryable through SDK
- [ ] Metrics are visible and accurate in UI

**Comment by wanglonghong** [comment]
we need to update events of SwapUtils because it doesn't have `canonicalId` in the events rn. cc @LayneHaber.

**Comment by wanglonghong** [comment]
> 

We should be able to fetch the events in both cases 

[case 1] - Internal StableSwap --> we need to update the events of swapUtils because all the events of swapUtils doesn't include `canonicalId`. cc @LayneHaber 

[case 2] - External StableSwap --> In case we deploy stableswap contract externally, we should be able to handle events in the same subgraph.
