### ISSUE TITLE
[router] 4.14 Use safe confirmations

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#161]

**Comment by rhlsthrm** [comment]
Get confirmations per chain. Also will need to check subgraph txs to make sure they are adequately confirmed.

**Comment by jakekidd** [comment]
This issue could actually be simpler than it appears. Since it's mostly an issue of UX, we want to encourage users to use appropriate confirmations. I propose a solution:
- Create a json file called "confirmations.json" (or something), where we detail the recommended number of confirmations for each chain, by chain ID. Obviously there's a LOT of chains (and new ones are created all the time), so keeping this up to date in the repo is a larger-ish ask. So on top of this, we...
- check the number of confirmations per chain in the getConfig, and validate that it's >1 (the default) IFF it's not specified in the confirmations.json. IFF it IS specified in confirmations.json, we then validate.

`recommended` -> recommended # of confirmations, from confirmations.json.
`confirmations` -> the value from the user's config.

       - `if (recommended === 1)`:
          > we don't care. this is probs a test chain; for 4 and 5 chain IDs, for example, we'll specify 1.
       - `if (recommended > 1 && confirmations < recommended)`:
          > **Log a warning!!** : We *could* error here, but what if the user knows what they are doing? Maybe we should have a configuration operation to override the confirmations.json (e.g. `overrideRecommendedConfirmations`).
       - `if (recommended > 1 && confirmations <== 1)`:
          > **ERROR: "Please specify a value other than the default. The recommended value is ${recommended}."**
       - `if (recommended == null && confirmations <== 1)`:
          > **ERROR: ...** : Same as above, minus recommended value message. This is the secret sauce to this system, since we won't have to worry about the "recommended" always being up-to-date. We basically let the user know "hey, you left this at the default, and that's *normally* unsafe*.

System has an added effect here : the demographic of users that fail to read/understand the appropriate configs here is probably the same demographic using the most common chains - chains that we'd probably have the recommendation specified for.

**Comment by LayneHaber** [comment]
> check the number of confirmations per chain in the getConfig, and validate that it's >1 (the default) IFF it's not specified in the confirmations.json. IFF it IS specified in confirmations.json, we then validate.

Default should always be more than 1, that's really not even sufficient for mainnet. IMO we should use `mainnet validation + 3` as a buffer

> Log a warning!! : We could error here, but what if the user knows what they are doing? Maybe we should have a configuration operation to override the confirmations.json (e.g. overrideRecommendedConfirmations)

Imo we should make the user explicitly confirm they are overriding safe recommendations. These are to prevent reorgs on one chain, which means someone is losing money if it happens.

> This is the secret sauce to this system, since we won't have to worry about the "recommended" always being up-to-date. We basically let the user know "hey, you left this at the default, and that's normally unsafe*.

I'm not sure why we would rely on the system having defaults that are "normally" unsafe. Whenever we provide defaults, we should consider it as the value we would use ourselves (since nobody will be as well informed about the system-wide implications as us).


Instead what I think we should do is keep a sensible default for known chains, and a bare minimum default that is based off of mainnet + a buffer (the assumption being the mainnet confirmations will be the lowest since they can have the shallowest reorgs). We can log a warning if the user specifically undercuts the recommended values && they have provided an indication that they intend to do so, and error otherwise.

**Comment by jakekidd** [comment]
> Default should always be more than 1, that's really not even sufficient for mainnet. IMO we should use mainnet validation + 3 as a buffer

I agree that's def not sufficient in most cases lol. I meant IFF it's **not** specified in the confirmations.json file. `mainnet + 3` makes perfect sense as a minimum to me.

> Imo we should make the user explicitly confirm they are overriding safe recommendations. These are to prevent reorgs on one chain, which means someone is losing money if it happens.

Cool, there will be a config option to `overrideRecommendedConfirmations` that will be set to `false` by default. As a result, this will error by default if the user did not put in sufficient confirmations! Otherwise, it will log a warning (unless it is explicitly specified in confirmations.json that the recommended confirmations IS 1, which would be the case for testnet chains).

> I'm not sure why we would rely on the system having defaults that are "normally" unsafe. Whenever we provide defaults, we should consider it as the value we would use ourselves (since nobody will be as well informed about the system-wide implications as us).

Instead what I think we should do is keep a sensible default for known chains, and a bare minimum default that is based off of mainnet + a buffer (the assumption being the mainnet confirmations will be the lowest since they can have the shallowest reorgs). We can log a warning if the user specifically undercuts the recommended values && they have provided an indication that they intend to do so, and error otherwise.

100%. Basically what i meant here actually, but in better words. I actually meant "normally" only in the context of, well, if you're testing on testnet chains it's probs fine lol, otherwise should be > 1

But let's make it > `mainnet + 3`

**Comment by jakekidd** [comment]
Adjusted logic:

```ts
const MIN_DEFAULT_CONFIRMATIONS = getMainnetConfirmationsReq() + 3;

for (chainId of chains) {
  recommended = recommended | MIN_DEFAULT_CONFIRMATIONS;
  if (confirmations < recommended) {
    if (config.overrideRecommendedConfirmations) {
      // log warning
    } else {
      throw;
    }
  }
}
```

**Comment by LayneHaber** [comment]
Cool this makes sense!

**Comment by rhlsthrm** [comment]
Let's add the confirmations info here: https://github.com/connext/chaindata/blob/main/crossChain.json
