### ISSUE TITLE
[contracts] Add EIP-1271 for sig recovery

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#188]
https://eips.ethereum.org/EIPS/eip-1271

**Comment by LayneHaber** [comment]
How would we have the contract be specified for the sending/receiving chain? How are we able to determine if its valid before accepting a transfer (imagining an attack vector where the user creates a transaction that is fulfillable on the receiving chain but not on the sending chain and steals from the router)?

Seems like (at a minimum) it would involve a few things:
1. Structuring the `TransactionManager` so that both EOA signing and contract signing is supported. This likely means altering the `InvariantTransactionData` to include both a `receivingRecoveryContract` and a `sendingRecoveryContract` address
2. Being able to validate these recovery contracts offchain. We can rely on the user being sufficiently motivated to properly input the `receivingRecoveryContract` variable, but the router would have to be able to test the `sendingRecoveryContract` before agreeing to lock up liquidity for a given transfer. I'm not sure what that looks like, or how we would be able to do it easily.

In my opinion this adds a degree of complexity that we don't necessarily want to include. What use cases would not having this lock us out from? Is there something else we can do to support those?

**Comment by LayneHaber** [comment]
Closing -- not worth adding additional complexity at this stage
