### ISSUE TITLE
As a team, we need to Enforce security on the SpokeConnector

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1926]
From epic #1808 

- [x]  Add watcher whitelist and associated updating functions to `SpokeConnector`
- [x]  Remove watcher whitelist and associated updating functions from `RootManager`
- [x]  Add `delayBlocks` to `SpokeConnector`
- [x]  Enforce `delayBlocks` has elapsed before processing messages from `aggregateRoot` on `SpokeConnector`
- [x]  Add a way for the owner to set the aggregate root when contract is disconnected
- [x]  Add ability to reenable contract to process from existing aggregate root

**Comment by liu-zhipeng** [comment]
`Remove watcher whitelist and associated updating functions from RootManager`
If we remove watcher whiltelist from `RootManager`, `removeConnector` function should be `onlyOwner`?

**Comment by rhlsthrm** [comment]
Updating scope here after a chat with @LayneHaber:

- Create a new contract called `WatcherManager` that gets deployed and both `SpokeConnector` and `RootManager` reference. This is so that the two contracts can share watchers on chains where both are deployed (i.e. mainnet).
- `delayBlocks` in `SpokeConnector` ensures that `proveAndProcess` cannot be called against a root that has not been sufficiently confirmed past `delayBlocks`.
- Use watchers to "pause" the `SpokeConnector` contracts from `proveAndProcess`ing.

Open question: 
How do we manage the latest confirmed root to prove against while allowing newer roots to be pushed in? If we allow the root to constantly be updated (this is an open function that can be called by anyone at any time), then we could effectively get DOSed by someone constantly update the root and not allow anything to be proven against it.

Option 1)
Store a `pending` and `committed` root. Do not allow `pending` to be updated unless `pending` has been elapsed and can be promoted to `committed`. i.e.
```
function updateAggregateRoot(new) {
  if (pending.confirm > block.number) {
      committed = pending;
      pending = new;
  } // else do nothing
} 
```
When proving against the root, check against both `pending` and `committed` in case pending has become confirmed. i.e.
```
function proveAndProcess(...) {
  rootToUse = pending.confirm > block.number ? pending : committed;
  ...
}
```
Pros: Very easy to implement.
Cons: Added latency.

Option 2)
Store all roots in storage and the number of roots stored. Then iterate through in a binary search to see which one is the most recent confirmed. Then store this count as a cursor for where to search from next time.
Example data structures:
```
uint postCount;
uint cursor;
mapping(index => root) roots;
mapping(root => acceptanceTime) timers;

// search between cursor and postCount.
// update cursor with the latest found postCount.
```
Pros: No restrictions on when roots can be posted. Least amount of latency.
Cons: More complex. Added gas for binary search.

Recommendation: Go with solution 1 for simplicity.
