### ISSUE TITLE
As a user, I need high level protocol documentation

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1955]
**Problem**
There should be a place to understand the protocol flow at a high level, this should include:

- Breakdown of transfer lifecycle
- How messages are passed + message lifecycle
- System architecture
- How rollup timeouts are bypassed

**Ideas to solve this**
Write the documentation, make sure to check whimsical for any helpful diagrams.

**Acceptance Criteria**

- [ ] Docs are live on the website

**Impact**
1. What OKR goal does this align to?
shipping amarok
2. Provide Impact estimate = ideally quantitative forecast, if not then qualitative description of impact 
10
**Other Notes**
A clear and concise description of what the problem is

**Comment by jakekidd** [comment]
@alexwhte not sure if we should breakout into sep. issue but would be great to include updating / polishing the READMEs for this.

**Comment by rhlsthrm** [comment]
For the initial audit-readiness milestone, I think we can keep everything in the [Notion doc](https://www.notion.so/connext/Contracts-Overview-aae61df225dd4606bfc21b8b811ea73b) since it's pretty well fleshed out. We can have a task for Beta/Teen Wolf which requires this to be ported onto the docs site.

**Comment by rhlsthrm** [comment]
> @alexwhte not sure if we should breakout into sep. issue but would be great to include updating / polishing the READMEs for this.

Definitely a task but not for audit-readiness/alpha.
