### ISSUE TITLE
As a user my bids should not just hang if a provider flakes out / has issues

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#620]
Router cannot cancel a transaction if the receiver chain is not configured because the safety-checks on the cancelled transaction require a provider. Could end up in a situation where the bid was accepted, then the router changed their configuration. 

Must either have a special method to cancel without performing safety checks, or ensure the transaction will properly transition to an `*Expired` status

**Comment by jakekidd** [comment]
This is a really tough edge case... could involve a future slashing condition, since it might be considered misbehavior on the router's part to basically abandon a chain after sending bids on it...

One idea: we could use default providers (like our default hardcoded subgraphs), maybe in chaindata/crossChain.json, and silently check unsupported chains on boot for stragglers to cancel in an effort to tidy up.

**Comment by rhlsthrm** [comment]
> One idea: we could use default providers (like our default hardcoded subgraphs), maybe in chaindata/crossChain.json, and silently check unsupported chains on boot for stragglers to cancel in an effort to tidy up.

Yeah, I think we should do this.

**Comment by alexwhte** [comment]
Closing per grooming @LayneHaber @rhlsthrm
