### ISSUE TITLE
[router/sequencer] Staging & production deployment

### ISSUE THREAD

**Issue by carlomazzaferro** [connext/nxtp#966]
## The Problem

Current CI deploys only testnet router and sequencer instance, to no particularly defined environment. We need an automated workflow to deploy a staging router/sequencer via Terraform (the current existing one), and one that deploys a production router/sequencer instance.

## The Solution

1.  Update the current workflow to deploy to `staging.testnet.squencer/router.connext.ninja`, on merges to `amarok`
2. A new workflow that deploys to `testnet.squencer/router.connext.ninja` on merges to amarok with git tags

Deployment will happen with the same steps as the testnet deployment (terraform validate / plan / apply) but using a different set of secrets & variables.

## Related

Secrets PR & Issue: #952 #919 
Discord discussion: https://discord.com/channels/454734546869551114/821070612054671391/963321634868039712

**Comment by rhlsthrm** [comment]
It took me a minute to understand the URL schema but I think this is correct lol:
`staging.testnet.{sequencer|router}.connext.ninja` would be another way to put it. We'll also need overrides in the configs for the contract and subgraph addresses for the staging ones, since the defaults will pull from the prod configs.
